CALCULATE(DISTINCTCOUNT('dbth WardStay'[SpellId]), USERELATIONSHIP('dbth WardStay'[DateEnd], Dates[Date]), FILTER('dbth WardStay', 'dbth WardStay'[WardCode] == "SAW" || 'dbth WardStay'[WardCode] == "SAU"))