COUNTROWS(
    CALCULATETABLE(
        filter('dbth WardStay', 'dbth WardStay'[WardCode] in { "ESAC", "ACU", "ACB"}),
        filter('dbth Attendance', 'dbth Attendance'[IsAmbulatoryCare]),
        USERELATIONSHIP(Dates[Date],'dbth WardStay'[DateEnd])
    )
)