{
  "name": "d370ed8e-5a15-4b48-9ccb-c5a635672092",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "dbth WardStay",
        "lineageTag": "e68ff9db-81e9-4e33-87ad-b218eef07006",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "73f77ba2-96cf-4b37-ac60-90e507dd9b97",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "SpellId",
            "dataType": "int64",
            "sourceColumn": "SpellId",
            "formatString": "0",
            "lineageTag": "0d26a85d-280f-4206-837a-03242d18f75e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "SpellId"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Start",
            "dataType": "dateTime",
            "sourceColumn": "Start",
            "formatString": "General Date",
            "lineageTag": "87ed9a84-343a-4932-8a70-1a446f77cff3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Start"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "End",
            "dataType": "dateTime",
            "sourceColumn": "End",
            "formatString": "General Date",
            "lineageTag": "6cad6eeb-1d67-472f-acf6-b221ba4af1fb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "End"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "WardCode",
            "dataType": "string",
            "sourceColumn": "WardCode",
            "lineageTag": "8aad4bf7-c158-4833-81f8-e7047c76a510",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "WardCode"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Number",
            "dataType": "int64",
            "sourceColumn": "Number",
            "formatString": "0",
            "lineageTag": "4715efeb-5372-47e6-9127-12e82ea12260",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Number"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NextWardCode1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "MINX(\n\tFILTER(\n\t\t'dbth WardStay',\n\t\t'dbth WardStay'[SpellId] = EARLIER('dbth WardStay'[SpellId]) && 'dbth WardStay'[Number] = EARLIER('dbth WardStay'[Number])+1),\n'dbth WardStay'[WardCode])",
            "lineageTag": "a0a1f250-6ee3-47c0-8055-f8da6e7f128a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NextWardCode2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "MINX(\n\tFILTER(\n\t\t'dbth WardStay',\n\t\t'dbth WardStay'[SpellId] = EARLIER('dbth WardStay'[SpellId]) && 'dbth WardStay'[Number] = EARLIER('dbth WardStay'[Number])+2),\n'dbth WardStay'[WardCode])",
            "lineageTag": "c64ac4ef-3dc9-480e-a5dd-37a5ba1c5e07",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NextWardCode3",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "MINX(\n\tFILTER(\n\t\t'dbth WardStay',\n\t\t'dbth WardStay'[SpellId] = EARLIER('dbth WardStay'[SpellId]) && 'dbth WardStay'[Number] = EARLIER('dbth WardStay'[Number])+3),\n'dbth WardStay'[WardCode])",
            "lineageTag": "32ca2056-102d-4537-bf2a-50fcbea35b5f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NextWardCode4",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "MINX(\n\tFILTER(\n\t\t'dbth WardStay',\n\t\t'dbth WardStay'[SpellId] = EARLIER('dbth WardStay'[SpellId]) && 'dbth WardStay'[Number] = EARLIER('dbth WardStay'[Number])+4),\n'dbth WardStay'[WardCode])",
            "lineageTag": "aeeb4c66-146b-464b-b8d7-7858454446b1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NextWardCode5",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "MINX(\n\tFILTER(\n\t\t'dbth WardStay',\n\t\t'dbth WardStay'[SpellId] = EARLIER('dbth WardStay'[SpellId]) && 'dbth WardStay'[Number] = EARLIER('dbth WardStay'[Number])+5),\n'dbth WardStay'[WardCode])",
            "lineageTag": "41b0354e-1da3-4d96-b8fa-fb251743f469",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "PrevWardCode",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "MAXX(\n\tFILTER(\n\t\t'dbth WardStay',\n\t\t'dbth WardStay'[SpellId] = EARLIER('dbth WardStay'[SpellId]) && 'dbth WardStay'[Number] = EARLIER('dbth WardStay'[Number])-1),\n'dbth WardStay'[WardCode])",
            "lineageTag": "2487edba-d541-49f9-9c8f-9d44b01b1a19",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "LoS_Days",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "DATEDIFF('dbth WardStay'[Start], 'dbth WardStay'[End], DAY)",
            "formatString": "0",
            "lineageTag": "bf3f1aed-4956-4e7f-92ef-3ac02881cd1c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "IsStay",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": "DATEDIFF('dbth WardStay'[Start], 'dbth WardStay'[End],HOUR) > 12",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "7d387b53-916d-4f99-a4d0-fd8b0d22854e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "DateStart",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "date(year('dbth WardStay'[Start]), MONTH('dbth WardStay'[Start]), day('dbth WardStay'[Start]))",
            "formatString": "General Date",
            "lineageTag": "16223452-7f41-45f2-a1fc-6375501b9c67",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "DateEnd",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "date(year('dbth WardStay'[End]), MONTH('dbth WardStay'[End]), day('dbth WardStay'[End]))",
            "formatString": "General Date",
            "lineageTag": "a881a466-19eb-4152-a16e-98506642aac9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "OrderYear",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "CALCULATE ( SELECTEDVALUE ( 'Dates'[Year] ) )",
            "formatString": "0",
            "lineageTag": "a7421fd7-51a9-441b-b8e5-8fecd1271210",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NextWardType1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "\n    var typeKind =  LOOKUPVALUE('dbth Ward'[TypeKind], 'dbth Ward'[WardCode], 'dbth WardStay'[NextWardCode1])\n    return If (IsBlank(typeKind), \"<discharged>\", typeKind)",
            "lineageTag": "093461b6-2845-4efb-825e-2529f74be435",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NextWardType2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "\n    var typeKind =  LOOKUPVALUE('dbth Ward'[TypeKind], 'dbth Ward'[WardCode], 'dbth WardStay'[NextWardCode2])\n    return If (IsBlank(typeKind), \"<discharged>\", typeKind)",
            "lineageTag": "c162e0dc-2003-409a-9c4b-ec9ef8ec6356",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NextWardName1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "\n    var typeKind =  LOOKUPVALUE('dbth Ward'[WardName], 'dbth Ward'[WardCode], 'dbth WardStay'[NextWardCode1])\n    return If (IsBlank(typeKind), \"<discharged>\", typeKind)",
            "lineageTag": "18549286-3414-478b-80af-e6eebc7a629a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NextWardName2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "\n    var typeKind =  LOOKUPVALUE('dbth Ward'[WardName], 'dbth Ward'[WardCode], 'dbth WardStay'[NextWardCode2])\n    return If (IsBlank(typeKind), \"<discharged>\", typeKind)",
            "lineageTag": "aaa189a2-22c4-4f35-8a7e-628f00b25f8e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "IsLastStayInSpell",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": "'dbth WardStay'[Number] == calculate(max('dbth WardStay'[Number]), allexcept('dbth WardStay', 'dbth WardStay'[SpellId]))",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "4863d8f2-9551-44bd-bd5e-cc5d82b20ba1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "PrevWardType",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "\n    var typeKind =  LOOKUPVALUE('dbth Ward'[TypeKind], 'dbth Ward'[WardCode], 'dbth WardStay'[PrevWardCode])\n    return If (IsBlank(typeKind), \"<direct admission>\", typeKind)",
            "lineageTag": "ec209b34-97ad-437d-ae0d-999f533f372c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "PrevWardName",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "\n    var wardName =  LOOKUPVALUE('dbth Ward'[WardName], 'dbth Ward'[WardCode], 'dbth WardStay'[PrevWardCode])\n    return If (IsBlank(wardName), \"<direct admission>\", wardName)",
            "lineageTag": "da7a0f55-1baa-4847-ae2c-36109d315903",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "ReadmittedTo",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "\n    if('dbth WardStay'[IsLastStayInSpell] == false(), blank(),  \n        VAR patientId = RELATED ( 'dbth Spell'[PatientIdHash] )\n        VAR spellId = RELATED ( 'dbth Spell'[Id] )\n        VAR stayEnd = 'dbth WardStay'[DateEnd]\n        VAR readmissionWindowEnd = stayEnd + 28\n        VAR readmissionSpells =\n            CALCULATETABLE (\n                'dbth WardStay',\n                'dbth WardStay'[Number] = 1,\n                'dbth WardStay'[DateStart] >= EARLIER ( 'dbth WardStay'[DateEnd] ),\n                'dbth WardStay'[DateStart] <= readmissionWindowEnd,\n                FILTER ( 'dbth WardStay', RELATED ( 'dbth Spell'[PatientIdHash] ) == patientId && RELATED ('dbth Spell'[Id]) <> spellId),\n                REMOVEFILTERS ( 'dbth WardStay' )\n            )\n            \n        VAR firstRow =\n            TOPN ( 1, readmissionSpells, 'dbth WardStay'[Start], true )\n            \n        RETURN\n            MAXX ( firstRow, 'dbth WardStay'[WardCode] )\n    )",
            "lineageTag": "9741c534-06c8-4309-b74d-ccffe38583c1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Readmitted to (WardName)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "LOOKUPVALUE('dbth Ward'[WardName],'dbth Ward'[WardCode], 'dbth WardStay'[ReadmittedTo])",
            "lineageTag": "f1ee450c-a7fc-4419-be64-a78a68758165",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth WardStay-61d9a9a2-1de4-468b-b1b5-4d5c738f0136",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_WardStay = Source{[Schema=\"dbth\",Item=\"WardStay\"]}[Data]\nin\n    dbth_WardStay"
            }
          }
        ],
        "measures": [
          {
            "name": "AvgWardStayLen",
            "expression": "\n    -- CALCULATE(AVERAGE('dbth WardStay'[LoS_Days]), 'dbth WardStay'[LoS_Days] > 0, USERELATIONSHIP(Dates[Date],'dbth WardStay'[DateStart]))\n    'dbth WardStay'[Bed Days in period (WS)] / 'dbth WardStay'[Active Ward Stays In Period]",
            "lineageTag": "8e6a891e-b89f-42de-9979-fc7bd740fcea",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Over12hStays",
            "expression": "CALCULATE(COUNT('dbth WardStay'[Id]), FILTER('dbth WardStay', 'dbth WardStay'[IsStay]))",
            "formatString": "0",
            "lineageTag": "05dadb10-5f20-4c24-b5ee-04eb88062d3f",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "KPI_AMU_Admissions",
            "expression": "CALCULATE(DISTINCTCOUNT('dbth WardStay'[SpellId]), USERELATIONSHIP('dbth WardStay'[DateEnd], Dates[Date]), FILTER('dbth WardStay', 'dbth WardStay'[WardCode] == \"AMU\"))",
            "formatString": "0",
            "lineageTag": "2031e8e8-0ea0-4dd6-8c50-5d65edcebf2b",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "KPI_Admissions",
            "expression": "CALCULATE(distinctCOUNT('dbth WardStay'[spellId]), USERELATIONSHIP('dbth WardStay'[DateStart], Dates[Date]))",
            "formatString": "0",
            "lineageTag": "80ac461e-c051-4d81-8ced-db635077493d",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "KPI_Frailty_Admissions",
            "expression": "CALCULATE(DISTINCTCOUNT('dbth WardStay'[SpellId]), USERELATIONSHIP('dbth WardStay'[DateEnd], Dates[Date]), FILTER('dbth WardStay', 'dbth WardStay'[WardCode] == \"FAU\" || 'dbth WardStay'[WardCode] == \"STIR\"))",
            "formatString": "0",
            "lineageTag": "45686aa6-f3e8-4f63-8550-ea5413df8e84",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "KPI_AMDU_Admissions",
            "expression": "CALCULATE(DISTINCTCOUNT('dbth WardStay'[SpellId]), USERELATIONSHIP('dbth WardStay'[DateEnd], Dates[Date]), FILTER('dbth WardStay', 'dbth WardStay'[WardCode] == \"AMDU\"))",
            "formatString": "0",
            "lineageTag": "e9426bc0-5d7f-4526-b5cc-d9a7be919bad",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "KPI_SAU_Admissions",
            "expression": "CALCULATE(DISTINCTCOUNT('dbth WardStay'[SpellId]), USERELATIONSHIP('dbth WardStay'[DateEnd], Dates[Date]), FILTER('dbth WardStay', 'dbth WardStay'[WardCode] == \"SAW\" || 'dbth WardStay'[WardCode] == \"SAU\"))",
            "formatString": "0",
            "lineageTag": "5b126181-5933-4517-9752-00b6399703f9",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "SDEC_WardStays",
            "expression": "COUNTROWS(\n    CALCULATETABLE(\n        filter('dbth WardStay', 'dbth WardStay'[WardCode] in { \"ESAC\", \"ACU\", \"ACB\"}),\n        USERELATIONSHIP(Dates[Date],'dbth WardStay'[DateEnd])\n    )\n)",
            "formatString": "0",
            "lineageTag": "79982f0a-81eb-497e-af24-dec14faf24dc",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "SDEC_WardStays_2",
            "expression": "COUNTROWS(\n    CALCULATETABLE(\n        filter('dbth WardStay', 'dbth WardStay'[WardCode] in { \"ESAC\", \"ACU\", \"ACB\"}),\n        filter('dbth Attendance', 'dbth Attendance'[IsAmbulatoryCare]),\n        USERELATIONSHIP(Dates[Date],'dbth WardStay'[DateEnd])\n    )\n)",
            "formatString": "0",
            "lineageTag": "a46d983b-1406-48f1-85a1-c90c7c4d22b6",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "First Ward Stay (in period)",
            "expression": "CALCULATE(distinctcount('dbth WardStay'[SpellId]),'dbth WardStay'[Number] == 1, USERELATIONSHIP('dbth Spell'[AdmittedDate], Dates[Date]))",
            "formatString": "0",
            "lineageTag": "585753ec-b9e8-49f0-8b57-d9231ba46de5",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Number of elderly ED patients in period",
            "expression": "\n    CALCULATE( \n        distinctCOUNT('dbth WardStay'[SpellId]), \n        Filter('dbth Attendance','dbth Attendance'[Age] >= 75),\n        USERELATIONSHIP('dbth Spell'[AdmittedDate], Dates[Date])\n)",
            "formatString": "0",
            "lineageTag": "10f47729-d2c5-4203-9627-20e8e4476f53",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Bed Days in period (WS)",
            "expression": "\n    var minDate = min(dates[date])\n    var maxDate = max(Dates[Date])\n    return calculate( sumx('dbth WardStay', DATEDIFF( max(mindate, 'dbth WardStay'[Start]), min(maxDate, 'dbth WardStay'[End]), DAY)), FILTER('dbth WardStay', 'dbth WardStay'[Start] < max(Dates[Date]) && 'dbth WardStay'[End] > min(dates[date])))",
            "formatString": "0",
            "lineageTag": "0a89e97b-b562-4559-acc1-cb2f7251a42e",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Active Ward Stays In Period",
            "expression": "CALCULATE(count('dbth WardStay'[Id]), FILTER('dbth WardStay', 'dbth WardStay'[DateStart] <= max(Dates[Date]) && 'dbth WardStay'[DateEnd] >= min(dates[date])))",
            "formatString": "0",
            "lineageTag": "aa9c5df3-5ce2-44ce-96cb-39eee8dbb4ca",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Bed days per ward stay",
            "expression": "'dbth WardStay'[Bed Days in period (WS)] / 'dbth WardStay'[Active Ward Stays In Period]",
            "lineageTag": "85a13836-6455-4608-8f99-30328ceebee4",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Active Spells (In Period)",
            "expression": "CALCULATE(distinctcount('dbth WardStay'[spellId]), 'dbth Spell'[IsZeroLen] == FALSE() ,FILTER('dbth WardStay', 'dbth WardStay'[DateStart] < max(Dates[Date]) && 'dbth WardStay'[DateEnd] >= min(dates[date])))",
            "formatString": "0",
            "lineageTag": "fc2444c9-02ee-4baa-9d5c-2dec49305004",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Share of patients over age 65",
            "expression": "CALCULATe([First Ward Stay (in period)],'dbth Attendance'[Age] > 65) / [First Ward Stay (in period)]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2c5bf106-fb43-45aa-8f1d-7b90ecc4ad2b",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "TEST_COMPARE_MONTHS",
            "expression": "if( DISTINCTCOUNT(Dates[YearMonth]) = 2, \"Analyze ALoS over time\", BLANK())",
            "lineageTag": "52267901-a0b6-4b83-bbdb-b65b6fbf6b28",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Deaths (%)",
            "expression": "[Deaths] / 'dbth WardStay'[Active Spells (In Period)]",
            "formatString": "0%;-0%;0%",
            "lineageTag": "f625e765-7dcb-431f-b7ec-a967179453a8",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"0\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Deaths",
            "expression": "CALCULATE('dbth WardStay'[Active Spells (In Period)], 'dbth DischargeMethod'[Code] = 4)",
            "formatString": "0",
            "lineageTag": "81f00971-59f2-4a18-9d02-3f63380a4e40",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Daily admissions",
            "expression": "[Active Spells (In Period)] / countrows(Dates)",
            "lineageTag": "c731ee47-848f-4ff7-b763-7ee306a079c0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Avg occupied beds",
            "expression": "'dbth WardStay'[Bed Days in period (WS)] / COUNTROWS(Dates)",
            "lineageTag": "d16b345a-49fe-4ecd-8198-2c14bda6f199",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Bed days per active spell",
            "expression": "'dbth WardStay'[Bed Days in period (WS)] / 'dbth WardStay'[Active Spells (In Period)]",
            "lineageTag": "97b7a33d-d0de-4a44-86e1-e266527ae264",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Avg beds",
            "expression": "'dbth WardStay'[Bed Days in period (WS)] / COUNTROWS(Dates)",
            "lineageTag": "9d034fa0-6e63-4b1a-ba19-6a7b8a0eee2e",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Active Ward Stays Patient Age In Period",
            "expression": "CALCULATE(average('dbth Attendance'[Age]) , FILTER('dbth WardStay', 'dbth WardStay'[DateStart] <= max(Dates[Date]) && 'dbth WardStay'[DateEnd] >= min(dates[date])))",
            "lineageTag": "e32f9ac8-d6dd-441c-9913-8b73909b6644",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dbth Spell",
        "lineageTag": "fe1c61ff-ad29-4008-8170-d5b8f10ea59f",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "f0c2f220-eb4b-4417-9c81-426ded0dd21d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "AttendanceId",
            "dataType": "int64",
            "sourceColumn": "AttendanceId",
            "formatString": "0",
            "lineageTag": "4d529265-388e-48db-9b37-9cea859729f6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "AttendanceId"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "PatientIdHash",
            "dataType": "string",
            "sourceColumn": "PatientIdHash",
            "lineageTag": "cea9df3a-fe41-45ee-93a6-9cdd7d256eba",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "PatientIdHash"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "AdministrativeCategory",
            "dataType": "int64",
            "sourceColumn": "AdministrativeCategory",
            "formatString": "0",
            "lineageTag": "3a6538f6-a211-46f9-a677-9fab68dd2842",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "AdministrativeCategory"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "AdmissionMethod",
            "dataType": "string",
            "sourceColumn": "AdmissionMethod",
            "lineageTag": "943db49d-9315-46a4-9832-fb41036b3e1f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "AdmissionMethod"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Admitted",
            "dataType": "dateTime",
            "sourceColumn": "Admitted",
            "formatString": "General Date",
            "lineageTag": "2c095439-b2ab-4cd5-a4ce-94f1b59f57be",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Admitted"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Discharged",
            "dataType": "dateTime",
            "sourceColumn": "Discharged",
            "formatString": "General Date",
            "lineageTag": "fa905cb0-19de-4240-b6a5-d69d6af2b043",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Discharged"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "DischargeDestination",
            "dataType": "int64",
            "sourceColumn": "DischargeDestination",
            "formatString": "0",
            "lineageTag": "41a88ce1-2999-4732-8f2a-eb634cb5f1d2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "DischargeDestination"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "DischargeMethod",
            "dataType": "int64",
            "sourceColumn": "DischargeMethod",
            "formatString": "0",
            "lineageTag": "9ef31bc7-b014-4317-b680-79bf16e3ffb7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "DischargeMethod"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "HospitalSiteCode",
            "dataType": "string",
            "sourceColumn": "HospitalSiteCode",
            "lineageTag": "01994936-9404-4c38-a830-06562a957946",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "HospitalSiteCode"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "PatientTypeCalc",
            "dataType": "string",
            "sourceColumn": "PatientTypeCalc",
            "lineageTag": "8fc26872-4d87-4ea5-959c-692bb99fd9f0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "PatientTypeCalc"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "SourceOfAdmission",
            "dataType": "int64",
            "sourceColumn": "SourceOfAdmission",
            "formatString": "0",
            "lineageTag": "f7a6aeec-3a6c-4699-b491-5a943b947219",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "SourceOfAdmission"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "AdmittedDate",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "date(year('dbth Spell'[Admitted]), month('dbth Spell'[Admitted]), day('dbth Spell'[Admitted]))",
            "formatString": "General Date",
            "lineageTag": "ae4c1c34-7b8c-4244-9a06-3d3bb8534f36",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "DischargedDate",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "date(year('dbth Spell'[Discharged]), month('dbth Spell'[Discharged]), day('dbth Spell'[Discharged]))",
            "formatString": "General Date",
            "lineageTag": "93e90b1e-00fa-498d-841f-5883df075b99",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "IsFromED",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": "ISBLANK('dbth Spell'[AttendanceId]) == FALSE()",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "01f00f27-cc7e-4e6f-930f-59e7e640c897",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Discharge Ward Type",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "\n    var lastNum = COUNTROWS(RELATEDTABLE('dbth WardStay'))\n    return CALCULATE(values('dbth Ward'[TypeKind]), filter(RELATEDTABLE('dbth WardStay'), 'dbth WardStay'[Number] = lastNum))",
            "lineageTag": "7012feeb-124b-4c06-801e-27b5d7d9f2cb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "LoS Days",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "DATEDIFF('dbth Spell'[AdmittedDate], 'dbth Spell'[DischargedDate], day)",
            "formatString": "0",
            "lineageTag": "fd4e145d-b6a4-42c5-84d8-844f554306c2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "IsZeroLen",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": "'dbth Spell'[LoS Days] = 0",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "5eb53743-ec6c-4548-8260-9229c7cf1ce9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth Spell-07008100-250b-4d88-9281-d1e6cd658ed7",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_Spell = Source{[Schema=\"dbth\",Item=\"Spell\"]}[Data],\n    #\"Removed Columns\" = Table.RemoveColumns(dbth_Spell,{\"DateDischargeEstimated\", \"DateDischargePlanned\", \"DateReadyForDischarge\"})\nin\n    #\"Removed Columns\""
            }
          }
        ],
        "measures": [
          {
            "name": "SpellsInPeriod",
            "expression": "CALCULATE(count('dbth Spell'[Id]), USERELATIONSHIP('dbth Spell'[AdmittedDate], Dates[Date]))",
            "formatString": "0",
            "lineageTag": "688e81d4-3450-4f57-914c-10f3e43c2973",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Readmissions",
            "expression": "\n    // if over this many days, it's not treated as a readmission\n    var readmissionDaysLimit = 28\n\n    return CALCULATE (\n        // find the number of ward stays\n        COUNTROWS( 'dbth WardStay'),\n        // taking into account only disrcharge wardstays (last wardstay in spell)\n        'dbth WardStay'[IsLastStayInSpell],\n        // such that there is one or more spells that started for the same patient within the designated window of time\n        FILTER (\n            'dbth Spell',\n            COUNTROWS (\n                CALCULATETABLE (\n                    'dbth Spell',\n                    REMOVEFILTERS(), // remove any filters from visuals such as breakdown by ward, the readmission doesn't necessarily have to be into the same ward\n                    FILTER (\n                        'dbth Spell',\n                        'dbth Spell'[PatientIdHash] = EARLIER ( 'dbth Spell'[PatientIdHash] )\n                            && 'dbth Spell'[Admitted] > EARLIER('dbth Spell'[Discharged])\n                            && ABS(datediff('dbth Spell'[Admitted], EARLIER('dbth Spell'[Discharged]), day)) <= readmissionDaysLimit\n                    )\n                )\n            ) > 0\n        ),\n        -- using discharge date for date filter\n        USERELATIONSHIP('dbth WardStay'[DateEnd], Dates[Date])\n    )",
            "formatString": "0",
            "lineageTag": "abeb0e2f-a160-4790-9199-66b576fbc241",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Readmission rate",
            "expression": "\n\n    var dischargedSpellsInPeriod = CALCULATE (\n        // find the number of ward stays\n        COUNTROWS( 'dbth WardStay'),\n        // taking into account only disrcharge wardstays (last wardstay in spell)\n        'dbth WardStay'[IsLastStayInSpell],\n        // using discharge date for date filter\n        USERELATIONSHIP('dbth WardStay'[DateEnd], Dates[Date])\n    )\n\n    return [Readmissions] / dischargedSpellsInPeriod",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dcfd43a9-f82d-4db9-ad96-146cb379dcd6",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Elderly ED Spells In Period",
            "expression": "CALCULATE(count('dbth Spell'[Id]), USERELATIONSHIP('dbth Spell'[AdmittedDate], Dates[Date]),'dbth Attendance'[Age] >= 75)",
            "formatString": "0",
            "lineageTag": "281ec7dc-1eff-47c8-872d-2a0cc05d22a0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "ALoS at discharge (with ward exclusions)",
            "expression": "\n    // todo: IsLoS exluded should be a column in the Ward table\n    var excludedWards = { \"PARK\",\"BARL\",\"BARA\",\"CLA\",\"KNVARA\",\"ONEHEALTH\", \"RHB1\", \"RHB2\", \"ON1\",\"PARK HILL\",\"PHO\",\"PIONEER\",\"PIONEERENT\",\"THORN\",                                 \"THORNBURY\",\"TRENT\",\"EPAU\",\"ECL\",\"DCL\",\"ED WARD\",\"DIS\" }\n    return calculate( \n        AVERAGEX(\n            'dbth Spell', \n            calculate(\n                sum ('dbth WardStay'[LoS_Days]), \n                'dbth WardStay'[WardCode] in excludedWards == false()\n            )\n        ), \n        'dbth Spell'[IsZeroLen] == FALSE(), \n        USERELATIONSHIP('dbth Spell'[DischargedDate], Dates[Date])\n    )",
            "lineageTag": "346e4177-9337-4040-9655-015982daa4a6",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Bed Days (in period)",
            "expression": "\n    var minDate = min(dates[date])\n    var maxDate = max(Dates[Date])\n    return \n        calculate( \n            sumx(\n                'dbth Spell', \n                DATEDIFF( \n                    max(mindate, 'dbth Spell'[AdmittedDate]), \n                    min(maxDate, 'dbth Spell'[DischargedDate]), DAY)\n            ), \n            FILTER(\n                'dbth Spell', \n                'dbth Spell'[AdmittedDate] < max(Dates[Date]) && 'dbth Spell'[DischargedDate] > min(dates[date])\n            )\n        )",
            "formatString": "0",
            "lineageTag": "14bbeb25-b58f-4a35-a5b0-1047e3068bc0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Bed days per patient",
            "expression": "'dbth Spell'[Bed Days (in period)] / 'dbth WardStay'[Active Spells (In Period)]",
            "lineageTag": "91ee83d9-5ce8-4199-82b6-f734e5c570f3",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Bed Days Per Spell (NZL)",
            "expression": "\n    \n    var bedDays_NZL_wardExlusions = calculate( \n        'dbth WardStay'[Bed Days in period (WS)],\n        'dbth Spell'[IsZeroLen] == FALSE()\n    )\n\n    var activeSpells = calculate( \n        'dbth WardStay'[Active Spells (In Period)],\n        'dbth Spell'[IsZeroLen] == FALSE()\n    )\n\n    return 1.0 * bedDays_NZL_wardExlusions / activeSpells\n",
            "formatString": "0",
            "lineageTag": "71a01b58-2895-4499-999d-8970b2bbdde0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Super stranded bed days",
            "expression": "\n    -- todo: define a column in \"Ward\" table for this\n    var excludedWards = { \"PARK\",\"BARL\",\"BARA\",\"CLA\",\"KNVARA\",\"ONEHEALTH\", \"RHB1\", \"RHB2\", \"ON1\",\"PARK HILL\",\"PHO\",\"PIONEER\",\"PIONEERENT\",\"THORN\", \"THORNBURY\",\"TRENT\",\"EPAU\",\"ECL\",\"DCL\",\"ED WARD\",\"DIS\" }\n\n    var daysBeforeStausKicksIn = 20\n    var minDate = min(Dates[Date])\n    var maxDate = max(dates[date])\n\n    return sumx(\n        'dbth Spell',\n\n        var activeDaysBeforePeriod =\n            CALCULATE (\n                SUMX (\n                    'dbth WardStay',\n                    (\n                        DATEDIFF ( 'dbth WardStay'[DateStart], min('dbth WardStay'[DateEnd], minDate), DAY)\n                    )\n                ),\n                'dbth WardStay'[WardCode] in excludedWards = false(),\n                'dbth WardStay'[DateStart] < minDate\n            )\n            \n        var daysTillSuperStranded = max(0, daysBeforeStausKicksIn - activeDaysBeforePeriod)\n            \n        var activeDaysInPeriod =\n            CALCULATE (\n                SUMX (\n                    'dbth WardStay',\n                    DATEDIFF ( max('dbth WardStay'[DateStart], minDate), min('dbth WardStay'[DateEnd], maxDate), DAY)\n                ),\n                'dbth WardStay'[WardCode] in excludedWards = false(),\n                'dbth WardStay'[DateEnd] >= minDate,\n                'dbth WardStay'[DateStart] <= maxDate\n            )\n        \n        return max(0, activeDaysInPeriod-daysTillSuperStranded)\n)",
            "formatString": "0",
            "lineageTag": "2b287607-db3e-4981-9a89-1b15cf5e4578",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Super Stranded Beds Share",
            "expression": "'dbth Spell'[Super stranded bed days] / 'dbth WardStay'[Bed Days in period (WS)]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e2292fac-2300-42c5-a032-b103a87419eb",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Stranded bed days",
            "expression": "\n    -- todo: define a column in \"Ward\" table for this\n    var excludedWards = { \"PARK\",\"BARL\",\"BARA\",\"CLA\",\"KNVARA\",\"ONEHEALTH\", \"RHB1\", \"RHB2\", \"ON1\",\"PARK HILL\",\"PHO\",\"PIONEER\",\"PIONEERENT\",\"THORN\", \"THORNBURY\",\"TRENT\",\"EPAU\",\"ECL\",\"DCL\",\"ED WARD\",\"DIS\" }\n\n    var daysBeforeStausKicksIn = 6\n    var minDate = min(Dates[Date])\n    var maxDate = max(dates[date])\n\n    return sumx(\n        'dbth Spell',\n\n        var activeDaysBeforePeriod =\n            CALCULATE (\n                SUMX (\n                    'dbth WardStay',\n                    (\n                        DATEDIFF ( 'dbth WardStay'[DateStart], min('dbth WardStay'[DateEnd], minDate), DAY)\n                    )\n                ),\n                'dbth WardStay'[WardCode] in excludedWards = false(),\n                'dbth WardStay'[DateStart] < minDate\n            )\n            \n        var daysTillSuperStranded = max(0, daysBeforeStausKicksIn - activeDaysBeforePeriod)\n            \n        var activeDaysInPeriod =\n            CALCULATE (\n                SUMX (\n                    'dbth WardStay',\n                    DATEDIFF ( max('dbth WardStay'[DateStart], minDate), min('dbth WardStay'[DateEnd], maxDate), DAY)\n                ),\n                'dbth WardStay'[WardCode] in excludedWards = false(),\n                'dbth WardStay'[DateEnd] >= minDate,\n                'dbth WardStay'[DateStart] <= maxDate\n            )\n        \n        return max(0, activeDaysInPeriod-daysTillSuperStranded)\n    ) - 'dbth Spell'[Super stranded bed days]",
            "formatString": "0",
            "lineageTag": "bb325361-f7bd-4c7a-a198-d1e13ec50b21",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Stranded Beds Share",
            "expression": "'dbth Spell'[Stranded bed days] / 'dbth WardStay'[Bed Days in period (WS)]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bc11bd71-612b-4053-b98d-b7f974e937b4",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Non stranded bed days",
            "expression": "'dbth WardStay'[Bed Days in period (WS)] - 'dbth Spell'[Stranded bed days] - 'dbth Spell'[Super stranded bed days]",
            "formatString": "0",
            "lineageTag": "273e99d6-4d77-42ca-9d89-9213dbbe9d49",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Non Stranded Beds Share",
            "expression": "[Non stranded bed days] / 'dbth WardStay'[Bed Days in period (WS)]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6b6f663b-0d04-41c0-a2c2-1ea89049c5fd",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Daily super-stranded",
            "expression": "'dbth Spell'[Super stranded bed days] / COUNTROWS(dates)",
            "lineageTag": "d5308d50-76ed-4c82-96ba-4c67e3b692c4",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Daily stranded",
            "expression": "'dbth Spell'[Stranded bed days] / COUNTROWS(dates)",
            "lineageTag": "f67d9f0e-23e7-491f-8aa6-5b086ee89880",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Daily non-stranded",
            "expression": "'dbth Spell'[non stranded bed days] / COUNTROWS(dates)",
            "lineageTag": "7bf60df5-06c2-4962-9be7-a2b311107f6d",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Average Super-Stranded Patient Age",
            "expression": "CALCULATE('dbth Attendance'[Age of ED attendance in period], filter('dbth Spell', CALCULATE( 'dbth Spell'[Super stranded bed days] ) > 0))",
            "formatString": "0",
            "lineageTag": "6a3025d3-918a-4e0e-9cf1-1d356a7a0f7f",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "ALoS at discharge (with ward exclusions) (Super-stranded)",
            "expression": "CALCULATE([ALoS at discharge (with ward exclusions)], filter('dbth Spell', CALCULATE('dbth Spell'[Super stranded bed days])>0))",
            "lineageTag": "086f5eb5-9d0b-4f92-be9a-6474976f6cb7",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Number of super-stranded spells",
            "expression": "CALCULATE('dbth Spell'[SpellsInPeriod], FILTER('dbth Spell', CALCULATE('dbth Spell'[Super stranded bed days]) > 0))",
            "formatString": "0",
            "lineageTag": "c4980de5-46b4-43c6-b104-fe36e5290b00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Average Stranded Patient Age",
            "expression": "CALCULATE('dbth Attendance'[Age of ED attendance in period], filter('dbth Spell', CALCULATE( 'dbth Spell'[Stranded bed days] ) > 0))",
            "lineageTag": "493b27d6-c108-4b7d-85e5-0ec76636360c",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Average Non-Stranded Patient Age",
            "expression": "CALCULATE('dbth Attendance'[Age of ED attendance in period], filter('dbth Spell', CALCULATE( 'dbth Spell'[Non stranded bed days] ) > 0))",
            "lineageTag": "5799bff6-59bf-41b4-bf79-ef1426b52fe4",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "super-stranded share of spells",
            "expression": "'dbth Spell'[Number of super-stranded spells] / 'dbth WardStay'[Active Spells (In Period)]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3be7b775-babd-4421-87d4-b9f83ddca7cc",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dbth SourceOfAdmission",
        "lineageTag": "512d45b7-8c9d-41d2-b4eb-d5d722c1c953",
        "columns": [
          {
            "name": "Code",
            "dataType": "int64",
            "sourceColumn": "Code",
            "formatString": "0",
            "lineageTag": "b1b2bc44-5850-4361-90f2-9f29daa2b523",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "abcbf7a5-277c-4764-be7d-3e8329c1ad7c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Description"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth SourceOfAdmission-62c0924b-e876-44f7-96b8-a37023ba8b6d",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_SourceOfAdmission = Source{[Schema=\"dbth\",Item=\"SourceOfAdmission\"]}[Data]\nin\n    dbth_SourceOfAdmission"
            }
          }
        ],
        "measures": [
          {
            "name": "Measure",
            "expression": "CALCULATE(count('dbth SourceOfAdmission'[Code]), 'dbth Spell')",
            "formatString": "0",
            "lineageTag": "ff7df3a1-7fdd-44f2-be61-1ef013433358",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dbth Episode",
        "lineageTag": "f43c0c29-edee-4a65-a08c-2af66516b3d0",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "aa9ff904-f466-4dd4-a4cc-6c332749f412",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "SpellId",
            "dataType": "int64",
            "sourceColumn": "SpellId",
            "formatString": "0",
            "lineageTag": "2d3ca61a-ef9d-4c44-a37e-5c70b8e6d669",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "SpellId"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "SourceSystem",
            "dataType": "string",
            "sourceColumn": "SourceSystem",
            "lineageTag": "fc8eb5b7-2714-4a13-832f-ae1050acb0aa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "SourceSystem"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "ConsultantMainSpecialty",
            "dataType": "int64",
            "sourceColumn": "ConsultantMainSpecialty",
            "formatString": "0",
            "lineageTag": "64b2cb33-2726-493e-9a0a-8c3d16958e2b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "ConsultantMainSpecialty"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Start",
            "dataType": "dateTime",
            "sourceColumn": "Start",
            "formatString": "General Date",
            "lineageTag": "9570a4e1-78fa-4460-9ee9-298e8da24f99",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Start"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "End",
            "dataType": "dateTime",
            "sourceColumn": "End",
            "formatString": "General Date",
            "lineageTag": "0c548bf5-3eb4-4e36-8d09-c975e2d4db85",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "End"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Number",
            "dataType": "int64",
            "sourceColumn": "Number",
            "formatString": "0",
            "lineageTag": "26fece22-5cf7-486c-b736-3d57cf5b66a8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Number"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "CodingStatus",
            "dataType": "string",
            "sourceColumn": "CodingStatus",
            "lineageTag": "053f4691-a1d3-4619-aaab-e0ff0605c902",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "DateStart",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "date(year('dbth Episode'[Start]), month('dbth Episode'[Start]), day('dbth Episode'[Start]))",
            "formatString": "General Date",
            "lineageTag": "925b7d06-a1e4-428e-be75-dffb93efe140",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "DateEnd",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "date(year('dbth Episode'[End]), month('dbth Episode'[End]), day('dbth Episode'[End]))",
            "formatString": "General Date",
            "lineageTag": "1ad13aad-1755-4c7a-a519-c70fcce4284a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth Episode-aac5c86b-2ba1-4fa7-9f6c-b4fef6c74871",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_Episode = Source{[Schema=\"dbth\",Item=\"Episode\"]}[Data]\nin\n    dbth_Episode"
            }
          }
        ],
        "measures": [
          {
            "name": "Episodes in perdiod",
            "expression": "CALCULATE(count('dbth Episode'[Id]), USERELATIONSHIP(Dates[date], 'dbth Episode'[DateStart]))",
            "lineageTag": "75616879-f70b-40f5-ae17-755a8039daa8"
          },
          {
            "name": "Episode Days in period",
            "expression": "\n    var minDate = min(dates[date])\n    var maxDate = max(Dates[Date])\n    return calculate( sumx('dbth episode', DATEDIFF( max(mindate, 'dbth Episode'[DateStart]), min(maxDate, 'dbth Episode'[DateEnd]), DAY)), FILTER('dbth WardStay', 'dbth WardStay'[Start] <= max(Dates[Date]) && 'dbth WardStay'[End] >= min(dates[date])))",
            "formatString": "0",
            "lineageTag": "593cf6a4-ec93-4faf-b16a-6469277dd853",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dbth DischargeMethod",
        "lineageTag": "7a2c2e41-2d5e-46c5-9a15-5cc4d0ec15e9",
        "columns": [
          {
            "name": "Code",
            "dataType": "int64",
            "sourceColumn": "Code",
            "formatString": "0",
            "lineageTag": "94d2fc18-11f7-4418-b085-1c59f5c3dda1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "be51c42e-dd5f-4257-bc0f-a305b7d0805b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Description"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth DischargeMethod-59a6cb4a-057a-4682-8f64-0b4f8d739391",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_DischargeMethod = Source{[Schema=\"dbth\",Item=\"DischargeMethod\"]}[Data]\nin\n    dbth_DischargeMethod"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dbth DischargeDestination",
        "lineageTag": "a1ea1e0e-5cbf-4994-9947-0afec2b17204",
        "columns": [
          {
            "name": "Code",
            "dataType": "int64",
            "sourceColumn": "Code",
            "formatString": "0",
            "lineageTag": "b73412c8-2a22-4f3d-9c3e-d4dace1b93bf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "dcac8fe0-9d37-470a-8fe7-7bfb89b86ba1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Description"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth DischargeDestination-5bb31d1e-0980-4b75-a478-37376f72745d",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_DischargeDestination = Source{[Schema=\"dbth\",Item=\"DischargeDestination\"]}[Data]\nin\n    dbth_DischargeDestination"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dbth AttendanceCategory",
        "lineageTag": "a68ab7c4-f9d7-475d-a571-11a55a05b27a",
        "columns": [
          {
            "name": "Code",
            "dataType": "int64",
            "sourceColumn": "Code",
            "formatString": "0",
            "lineageTag": "dcebd23b-9d1d-4d27-8489-ee00128d70ac",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "72850f8c-58e2-4f2c-a22b-939337e640f7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Description"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth AttendanceCategory-8fbbb449-7be2-4e7c-94ba-1d4409acbeb0",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_AttendanceCategory = Source{[Schema=\"dbth\",Item=\"AttendanceCategory\"]}[Data]\nin\n    dbth_AttendanceCategory"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dbth Attendance",
        "lineageTag": "ae6666ee-a469-4173-a93b-12ff7b7d9bfa",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "4e4c3f0a-56f1-4beb-a04f-c300a9030002",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Id"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "SpellId",
            "dataType": "int64",
            "sourceColumn": "SpellId",
            "formatString": "0",
            "lineageTag": "5798ec6f-124c-46f5-b32a-7df53063d358",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "SpellId"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "PatientIdHash",
            "dataType": "string",
            "sourceColumn": "PatientIdHash",
            "lineageTag": "37bac0bf-fb29-489b-9a00-4f5a416eaea0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "PatientIdHash"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Age",
            "dataType": "int64",
            "sourceColumn": "Age",
            "formatString": "0",
            "lineageTag": "f34687d7-b7e4-4cf3-b1eb-4c1d438e1dcf",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Age"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "ArrivalMode",
            "dataType": "int64",
            "sourceColumn": "ArrivalMode",
            "formatString": "0",
            "lineageTag": "26c37783-cf6c-42db-9ea9-aba072ad30e9",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "ArrivalMode"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "ArrivalModelSys",
            "dataType": "string",
            "sourceColumn": "ArrivalModelSys",
            "lineageTag": "f4bf7a8e-c850-4e2d-b4d9-0b25b368accc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "ArrivalModelSys"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "AttendanceCategory",
            "dataType": "int64",
            "sourceColumn": "AttendanceCategory",
            "formatString": "0",
            "lineageTag": "fa73d05f-829c-459e-b23b-42b72820a8bd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "AttendanceCategory"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Arrived",
            "dataType": "dateTime",
            "sourceColumn": "Arrived",
            "formatString": "General Date",
            "lineageTag": "cdc21216-69a3-4605-848c-e35648397a5f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Arrived"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Admitted",
            "dataType": "dateTime",
            "sourceColumn": "Admitted",
            "formatString": "General Date",
            "lineageTag": "9281a5c1-dd27-424a-a95b-ee9017a5c53c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Admitted"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "AdmittedCDU",
            "dataType": "dateTime",
            "sourceColumn": "AdmittedCDU",
            "formatString": "General Date",
            "lineageTag": "55746087-e749-4f92-bff0-010ce059821e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "AdmittedCDU"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Clerked",
            "dataType": "dateTime",
            "sourceColumn": "Clerked",
            "formatString": "General Date",
            "lineageTag": "0de36142-c7fa-4ec7-a07e-d4b8b6fecfdc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Clerked"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Departed",
            "dataType": "dateTime",
            "sourceColumn": "Departed",
            "formatString": "General Date",
            "lineageTag": "67a5b03c-80ef-4678-a694-9a98f02b22ab",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Departed"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "AssesmentStart",
            "dataType": "dateTime",
            "sourceColumn": "AssesmentStart",
            "formatString": "General Date",
            "lineageTag": "a1a67585-d482-4f3d-adb3-79afe341da4e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "AssesmentStart"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "AssesmentEnd",
            "dataType": "dateTime",
            "sourceColumn": "AssesmentEnd",
            "formatString": "General Date",
            "lineageTag": "cc427077-eac3-4d30-905f-fec97f5d32c9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "AssesmentEnd"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "SeenByDoctor",
            "dataType": "dateTime",
            "sourceColumn": "SeenByDoctor",
            "formatString": "General Date",
            "lineageTag": "09434bdd-3894-4c9e-bccc-30c13b79b565",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "SeenByDoctor"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "SeenByNurse",
            "dataType": "dateTime",
            "sourceColumn": "SeenByNurse",
            "formatString": "General Date",
            "lineageTag": "144b7de2-588c-41f7-a2f8-d2cbb4f4aac6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "SeenByNurse"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "SeenForTreatment",
            "dataType": "dateTime",
            "sourceColumn": "SeenForTreatment",
            "formatString": "General Date",
            "lineageTag": "f948b63f-6e92-42a0-8f14-9c63c823ebc9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "SeenForTreatment"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "DepartmentType",
            "dataType": "int64",
            "sourceColumn": "DepartmentType",
            "formatString": "0",
            "lineageTag": "df21007b-9acf-40c4-ade2-bc09630fbbef",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "DepartmentType"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "DepartureDestination",
            "dataType": "int64",
            "sourceColumn": "DepartureDestination",
            "formatString": "0",
            "lineageTag": "6eefbd8b-2f36-49d4-902a-81739beacc7e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "DepartureDestination"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Site",
            "dataType": "string",
            "sourceColumn": "Site",
            "lineageTag": "cd167286-f21d-462b-88c3-51ff2f01a5a5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Site"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Stream",
            "dataType": "string",
            "sourceColumn": "Stream",
            "lineageTag": "b48d71e6-233f-473d-9b18-f8ee888ba3db",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Stream"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "IsAmbulatoryCare",
            "dataType": "boolean",
            "sourceColumn": "IsAmbulatoryCare",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "91fcdf9e-0d1a-42a3-923c-196830632e07",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Boolean#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "IsAmbulatoryCare"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "ArrivedDate",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "date(year('dbth Attendance'[Arrived]), month('dbth Attendance'[Arrived]), day('dbth Attendance'[Arrived]))",
            "formatString": "General Date",
            "lineageTag": "e4d474c2-8f83-4c01-bdf9-004359a60fa1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "AttendanceDisposalCode",
            "dataType": "int64",
            "sourceColumn": "AttendanceDisposalCode",
            "formatString": "0",
            "lineageTag": "a835f58c-fb9e-45b1-b35b-e9e535519987",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "ArrivalModeText",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "SWITCH('dbth Attendance'[ArrivalMode], 1, \"Ambulance\", 2, \"Other\", BLANK())",
            "lineageTag": "7450d05c-906f-41ea-858c-22872513ee95",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth Attendance-da5d2828-9420-440b-a05a-cbde0eea9b65",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_Attendance = Source{[Schema=\"dbth\",Item=\"Attendance\"]}[Data]\nin\n    dbth_Attendance"
            }
          }
        ],
        "measures": [
          {
            "name": "KPI_ED_Arrivals",
            "expression": "CALCULATE(COUNT('dbth Attendance'[Id]), USERELATIONSHIP('dbth Attendance'[Site],'dbth HospitalSite'[Code]) , USERELATIONSHIP('dbth Attendance'[ArrivedDate], Dates[Date]))",
            "formatString": "0",
            "lineageTag": "a097ca36-7efd-4da4-b08a-e6f2af44797b",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Attendances In Period",
            "expression": "calculate( COUNT('dbth Attendance'[Id]), USERELATIONSHIP(Dates[Date],'dbth Attendance'[ArrivedDate]))",
            "formatString": "0",
            "lineageTag": "7d109721-3bf8-4a0f-9038-d10f820cbae5",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Age of ED attendance in period",
            "expression": "calculate( AVERAGE('dbth Attendance'[Age]), USERELATIONSHIP(Dates[Date],'dbth Attendance'[ArrivedDate]))",
            "lineageTag": "3eafb950-3363-49e0-b8cd-c043495dedae",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "Attendance in period",
            "expression": "CALCULATE(count('dbth Attendance'[Id]), USERELATIONSHIP(Dates[Date],'dbth Attendance'[ArrivedDate]))",
            "formatString": "0",
            "lineageTag": "d8eb8f2c-0fdc-4c1f-868c-18f117582d85",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Share of attendance over age 65 in period",
            "expression": "calculate('dbth Attendance'[Attendance in period],'dbth Attendance'[Age] > 65) / 'dbth Attendance'[Attendance in period]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f2701e60-aade-4f90-88ec-8a86136cf14c",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"2\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dbth AdmissionMethod",
        "lineageTag": "a0393f85-ae1c-4c52-b112-fb3161a26872",
        "columns": [
          {
            "name": "Code",
            "dataType": "string",
            "sourceColumn": "Code",
            "lineageTag": "1db13c25-9d07-4c31-bc55-9ec8b8e55553",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "ecfff809-fb54-4d29-b04a-9128f66a2f14",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Description"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth AdmissionMethod-0ed87f57-2c09-4fa0-8438-f3aca16f4fbd",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_AdmissionMethod = Source{[Schema=\"dbth\",Item=\"AdmissionMethod\"]}[Data]\nin\n    dbth_AdmissionMethod"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dbth AdministrativeCategory",
        "lineageTag": "429df64e-b1ec-4fa8-b661-c176f99707e4",
        "columns": [
          {
            "name": "Code",
            "dataType": "int64",
            "sourceColumn": "Code",
            "formatString": "0",
            "lineageTag": "286e62c5-83d2-4c8a-8439-46694e2a6242",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "6e454be6-10e2-409b-8a3b-83c414a8f847",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Description"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth AdministrativeCategory-8a5182be-646a-498d-8c73-c54d480fbd54",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_AdministrativeCategory = Source{[Schema=\"dbth\",Item=\"AdministrativeCategory\"]}[Data]\nin\n    dbth_AdministrativeCategory"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_DescriptionAtRefresh"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dbth Ward",
        "lineageTag": "40987abf-f635-427f-810d-e30a2fb64430",
        "columns": [
          {
            "name": "SYSSourceSystem",
            "dataType": "string",
            "sourceColumn": "SYSSourceSystem",
            "lineageTag": "5575fad1-cf36-44f1-8368-a64968852d2d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "AgeGroupIntendedCode",
            "dataType": "int64",
            "sourceColumn": "AgeGroupIntendedCode",
            "lineageTag": "bf8dadb7-b256-4167-b4d7-7db766d3fe51",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "AvailableCountDays",
            "dataType": "double",
            "sourceColumn": "AvailableCountDays",
            "lineageTag": "71c367fc-2704-4d06-a81e-3dde72044008",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "AvailableCountNights",
            "dataType": "double",
            "sourceColumn": "AvailableCountNights",
            "lineageTag": "24e17990-aa3f-4891-947f-4a263be766bd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "BedCountNurse",
            "dataType": "double",
            "sourceColumn": "BedCountNurse",
            "lineageTag": "0a357a3f-2439-4c33-924b-1986ec552859",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "BedCountConsultant",
            "dataType": "double",
            "sourceColumn": "BedCountConsultant",
            "lineageTag": "5fd7907c-e5fc-416a-92ec-50bcc1a39f3d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "DateFrom",
            "dataType": "dateTime",
            "sourceColumn": "DateFrom",
            "formatString": "General Date",
            "lineageTag": "8760674a-5fdd-418c-9235-e8c7eff24acd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "DateTo",
            "dataType": "string",
            "sourceColumn": "DateTo",
            "lineageTag": "2ea575ad-003c-4476-b591-fa7499027a0b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "DayNightAvailabilityDescription",
            "dataType": "string",
            "sourceColumn": "DayNightAvailabilityDescription",
            "lineageTag": "93612d13-59bc-468f-8a6a-810ca7d3e1ad",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "SexGroupDescription",
            "dataType": "string",
            "sourceColumn": "SexGroupDescription",
            "lineageTag": "dffbf3ad-230e-4a86-94f3-a1b83eca1c6d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "SexOfPatientsCode",
            "dataType": "double",
            "sourceColumn": "SexOfPatientsCode",
            "lineageTag": "8ac2778e-fb96-4aaa-8ede-62fc19508e56",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              }
            ]
          },
          {
            "name": "SMTWTFSAvailabilityMatrixDay",
            "dataType": "string",
            "sourceColumn": "SMTWTFSAvailabilityMatrixDay",
            "lineageTag": "06933504-6832-413e-b31e-4125adbffcc8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "SMTWTFSAvailabilityMatrixNight",
            "dataType": "string",
            "sourceColumn": "SMTWTFSAvailabilityMatrixNight",
            "lineageTag": "2bfb0e88-e0bd-4313-9132-62d200287864",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "WardCode",
            "dataType": "string",
            "sourceColumn": "WardCode",
            "lineageTag": "bdd13c5d-f8ea-4b7c-bbd9-404fd1bf6c1c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "WardName",
            "dataType": "string",
            "sourceColumn": "WardName",
            "lineageTag": "668f8e53-5eaf-4a99-ba25-fdfcdf899aec",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "HospitalCode",
            "dataType": "string",
            "sourceColumn": "HospitalCode",
            "lineageTag": "818b8022-75f9-4d70-ad8c-6b7c7e3ebee8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "IntendedClinicalCareIntensityCode",
            "dataType": "int64",
            "sourceColumn": "IntendedClinicalCareIntensityCode",
            "formatString": "0",
            "lineageTag": "0a5c112b-5a73-4660-b0e4-166cfb50f5ac",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "Type",
            "lineageTag": "7eec76f2-0b2b-4a1c-a9f4-563317e831b1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Kind",
            "dataType": "string",
            "sourceColumn": "Kind",
            "lineageTag": "42eb5f5a-a640-4a4d-96a0-0ce7638d98c3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "TypeKind",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "if(isblank('dbth Ward'[Kind]),  'dbth Ward'[Type], 'dbth Ward'[Kind])",
            "lineageTag": "ad0fd5a6-eb68-480a-b5b3-566e652ebc53",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth Ward-bc249986-19fd-42ec-a9c3-c1a4944735c3",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_Ward = Source{[Schema=\"dbth\",Item=\"Ward\"]}[Data]\nin\n    dbth_Ward"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dates",
        "lineageTag": "8db70ae5-ebb4-4659-86d5-87ecd3e8846c",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isKey": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "0ec4d862-f5c0-4b4e-87bc-e8620012511e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralDateTimeLong\" FormatString=\"G\" /></DateTimes></Format>"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Dates\",\"TableItemName\":\"YearMonth\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"Dates\",\"TableItemName\":\"Date (bins)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Year]",
            "formatString": "0",
            "lineageTag": "0c12f964-61bb-4ffc-93c9-ed9bfaed917d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Month]",
            "sortByColumn": "MonthNumber",
            "lineageTag": "85f66461-74d4-4fe9-bd38-c339d1cd1988",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"SortByColumn\"]"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Week num",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Week num]",
            "formatString": "0",
            "lineageTag": "d8384fe4-b6f1-4f24-9ec3-7217e1f8df7d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthNumber",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[MonthNumber]",
            "formatString": "0",
            "lineageTag": "93554bbe-d219-470c-a19b-a1bf29604ced",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "YearMonth",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "IF(\n  ISBLANK('Dates'[Date]),\n  BLANK(),\n  DATE(\n    YEAR('Dates'[Date]),\n    1 + (MONTH('Dates'[Date]) - 1),\n    1\n  )\n)",
            "formatString": "mmmm yyyy",
            "lineageTag": "47a985b9-d051-4636-bd06-006ce5185edd",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "GroupingMetadata",
                "value": {
                  "version": 0,
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Dates"
                          }
                        },
                        "Property": "Date"
                      }
                    }
                  ],
                  "binningMetadata": {
                    "binSize": {
                      "value": 1.0,
                      "unit": 6
                    }
                  }
                }
              }
            ],
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"d\",\"Entity\":\"Dates\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"d\"}},\"Property\":\"Date\"}}],\"BinItem\":{\"Expression\":{\"Floor\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"d\"}},\"Property\":\"Date\"}},\"Size\":1.0,\"TimeUnit\":2}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"YearMonth\" FormatString=\"MMMM yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "PBI_FormatHint",
                "value": "DateTimeCustom"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Date (bins)",
            "dataType": "dateTime",
            "expression": "IF(\n  ISBLANK('Dates'[Date]),\n  BLANK(),\n  1 + (INT((INT('Dates'[Date]) - 1) / 7) * 7)\n)",
            "formatString": "Short Date",
            "lineageTag": "41c95bc2-ca70-4f2d-8d2f-ebd2e45f47a4",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "GroupingMetadata",
                "value": {
                  "version": 0,
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Dates"
                          }
                        },
                        "Property": "Date"
                      }
                    }
                  ],
                  "binningMetadata": {
                    "binSize": {
                      "value": 7.0,
                      "unit": 8
                    }
                  }
                }
              }
            ],
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"d\",\"Entity\":\"Dates\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"d\"}},\"Property\":\"Date\"}}],\"BinItem\":{\"Expression\":{\"Floor\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"d\"}},\"Property\":\"Date\"}},\"Size\":7.0,\"TimeUnit\":0}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"d\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Is in last 3 calendar months",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": "dates[date] > EOMONTH(calculate(max(dates[Date]), REMOVEFILTERS()), -3)",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "8c244d1c-ac0a-48e0-9163-398599532155",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Is in last calendar year",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": "year(dates[date]) = year(calculate(max(dates[Date]), REMOVEFILTERS()))",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3fad2530-e6d1-4d84-9ebf-7610f4b2ad94",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Boolean\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "CalendarMonthOrderFromLastDate",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "-DATEDIFF(dates[date], calculate(max(dates[date]), REMOVEFILTERS()), MONTH)",
            "formatString": "0",
            "lineageTag": "02d0f711-ed88-447e-9fa0-c7e8ae7cd4a2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dates-9430a3a2-ebbb-483b-8ce7-e209c0402be4",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "ADDCOLUMNS (\n    CALENDAR(min('dbth Spell'[Discharged]), max('dbth Spell'[Discharged])),\n    \"Year\", YEAR ( [Date] ),\n    \"MonthNumber\", Month ( [Date]),\n    \"Month\", FORMAT ( [Date], \"mmmm\" ),\n    \"Week num\", WEEKNUM([Date],1)\n)"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "375121ef-757e-47fc-a4bb-cf9899755e7e",
            "levels": [
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Month",
                "lineageTag": "8d90ad43-15c2-44c8-8a47-e416b3868172"
              },
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "d0816a88-4b70-44bc-b379-274c7a497ae2"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date",
                "lineageTag": "5616fccb-184e-4722-bfe4-ed734f866414"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6648e37713934aadb057f78286eb0cbf"
          }
        ]
      },
      {
        "name": "dbth MainSpecialty",
        "lineageTag": "a04f6dee-9c0d-41b3-b739-080dd92d08af",
        "columns": [
          {
            "name": "Code",
            "dataType": "int64",
            "sourceColumn": "Code",
            "formatString": "0",
            "lineageTag": "9e2879f3-19b0-4df6-a293-54da606bd1e0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "2d60f32a-c1fb-4587-9866-27dd7eb9b04e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth MainSpecialty-0fb6274c-2f8e-4e8b-92d3-4057bf94b7d6",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_MainSpecialty = Source{[Schema=\"dbth\",Item=\"MainSpecialty\"]}[Data]\nin\n    dbth_MainSpecialty"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dbth AttendanceDisposal",
        "lineageTag": "5384e30e-25dd-4ecb-b03e-7dc1d3d980bc",
        "columns": [
          {
            "name": "Code",
            "dataType": "int64",
            "sourceColumn": "Code",
            "formatString": "0",
            "lineageTag": "bee20967-0cb1-427d-9819-12509fdfc0bb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "43fa9d18-c6c1-4483-8b43-72b77baae1c4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "lineageTag": "3fe86ed7-2b53-4f11-824e-446ff0280615",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth AttendanceDisposal-193a7b72-b2cf-43e6-b05a-db522c7d7162",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_AttendanceDisposal = Source{[Schema=\"dbth\",Item=\"AttendanceDisposal\"]}[Data]\nin\n    dbth_AttendanceDisposal"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dbth HospitalSite",
        "lineageTag": "d0c80c41-cd3b-4cdc-ba63-7dcd794b5d15",
        "columns": [
          {
            "name": "Code",
            "dataType": "string",
            "sourceColumn": "Code",
            "lineageTag": "8978e92c-9769-4aea-a875-b65ea112f03e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "27fea52a-282d-4adb-a6a5-4caf5c8cc022",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth HospitalSite-625fbd8a-3664-42cc-bd5a-4e299a0f5e39",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_HospitalSite = Source{[Schema=\"dbth\",Item=\"HospitalSite\"]}[Data]\nin\n    dbth_HospitalSite"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dbth WardIntendedAgeGroup",
        "lineageTag": "9a3ccad7-1425-43d9-b696-1bd69559c70d",
        "columns": [
          {
            "name": "Code",
            "dataType": "int64",
            "sourceColumn": "Code",
            "formatString": "0",
            "lineageTag": "aac2f00b-4848-4e6e-b39a-124ec24c5e14",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "7d60c36f-81ca-48a5-a45d-064881dad082",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth WardIntendedAgeGroup-a968774b-8c82-4bcc-9073-1e32c98176e3",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_WardIntendedAgeGroup = Source{[Schema=\"dbth\",Item=\"WardIntendedAgeGroup\"]}[Data]\nin\n    dbth_WardIntendedAgeGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dbth WardIntendedClinicalCareIntensity",
        "lineageTag": "594e8350-a8b3-41cf-861a-aeeb7a1c33aa",
        "columns": [
          {
            "name": "Code",
            "dataType": "int64",
            "sourceColumn": "Code",
            "formatString": "0",
            "lineageTag": "342dba40-4b97-4ccb-96be-ef48ba7332aa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              }
            ]
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "lineageTag": "62361de2-181f-4fb8-a357-42e9e44971e9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dbth WardIntendedClinicalCareIntensity-bc1f50b7-20ad-4bfc-9702-9d8f3eee4965",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"20.117.159.235\", \"Dataflow\"),\n    dbth_WardIntendedClinicalCareIntensity = Source{[Schema=\"dbth\",Item=\"WardIntendedClinicalCareIntensity\"]}[Data]\nin\n    dbth_WardIntendedClinicalCareIntensity"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "e357f34b-5961-499c-bc34-8fdec4d50db7",
        "fromTable": "dbth WardStay",
        "fromColumn": "SpellId",
        "toTable": "dbth Spell",
        "toColumn": "Id",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "38acac20-0146-4a18-846b-6bee54c59f81",
        "fromTable": "dbth Spell",
        "fromColumn": "AdministrativeCategory",
        "toTable": "dbth AdministrativeCategory",
        "toColumn": "Code",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "25e716f0-ff97-4c8c-8ffc-6b97fce00110",
        "fromTable": "dbth Spell",
        "fromColumn": "AdmissionMethod",
        "toTable": "dbth AdmissionMethod",
        "toColumn": "Code",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "678ff800-4eb5-4968-a02a-78f2c2b7c39a",
        "fromTable": "dbth Spell",
        "fromColumn": "AttendanceId",
        "toTable": "dbth Attendance",
        "toColumn": "Id",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "824d7250-cda0-4a7f-b74b-3a0918869cb5",
        "fromTable": "dbth Spell",
        "fromColumn": "DischargeDestination",
        "toTable": "dbth DischargeDestination",
        "toColumn": "Code",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "3ecbbbcc-57c2-431e-ad0c-d931d308038c",
        "fromTable": "dbth Spell",
        "fromColumn": "DischargeMethod",
        "toTable": "dbth DischargeMethod",
        "toColumn": "Code",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "865e4e13-4632-45d5-9b27-09b154b150cd",
        "fromTable": "dbth Episode",
        "fromColumn": "SpellId",
        "toTable": "dbth Spell",
        "toColumn": "Id",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "434b4906-4d9f-471f-9b8b-6e948ddbffb7",
        "fromTable": "dbth Spell",
        "fromColumn": "SourceOfAdmission",
        "toTable": "dbth SourceOfAdmission",
        "toColumn": "Code",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "16e0c779-37b8-4bdb-a6a6-47a3f3dcb046",
        "fromTable": "dbth Attendance",
        "fromColumn": "AttendanceCategory",
        "toTable": "dbth AttendanceCategory",
        "toColumn": "Code",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "1a28bac6-0bb4-4826-8df8-db829d17e79e",
        "fromTable": "dbth WardStay",
        "fromColumn": "WardCode",
        "toTable": "dbth Ward",
        "toColumn": "WardCode"
      },
      {
        "name": "05bcf017-6875-41a1-939d-1d6a4247bcc9",
        "fromTable": "dbth Spell",
        "fromColumn": "DischargedDate",
        "toTable": "Dates",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "4e51a3d9-82d0-4d4f-bc6e-298053241030",
        "fromTable": "dbth Spell",
        "fromColumn": "AdmittedDate",
        "toTable": "Dates",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "0e0b47d2-451a-4dc0-adaa-9f046c53eaa9",
        "fromTable": "dbth Attendance",
        "fromColumn": "ArrivedDate",
        "toTable": "Dates",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "c2a69b12-0925-437a-9ba9-2f7cbee56ada",
        "fromTable": "dbth WardStay",
        "fromColumn": "DateEnd",
        "toTable": "Dates",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "832a4e00-9c17-49b3-8f2d-2878259ebe28",
        "fromTable": "dbth WardStay",
        "fromColumn": "DateStart",
        "toTable": "Dates",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "8ba85e6d-f037-4e66-a02c-1ba2d469c7a7",
        "fromTable": "dbth Episode",
        "fromColumn": "ConsultantMainSpecialty",
        "toTable": "dbth MainSpecialty",
        "toColumn": "Code",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "9c76c612-23e8-4023-9598-18ab12e7b6f5",
        "fromTable": "dbth Spell",
        "fromColumn": "HospitalSiteCode",
        "toTable": "dbth HospitalSite",
        "toColumn": "Code",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "f2d66198-0976-43e5-9167-507afbd75a23",
        "fromTable": "dbth Ward",
        "fromColumn": "HospitalCode",
        "toTable": "dbth HospitalSite",
        "toColumn": "Code",
        "isActive": false,
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "8ee4aafb-4ae8-4ce9-80fa-831a2e756c26",
        "fromTable": "dbth Ward",
        "fromColumn": "AgeGroupIntendedCode",
        "toTable": "dbth WardIntendedAgeGroup",
        "toColumn": "Code",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "bae31e5f-3d61-47e2-ad71-baaa0177d6c8",
        "fromTable": "dbth Ward",
        "fromColumn": "IntendedClinicalCareIntensityCode",
        "toTable": "dbth WardIntendedClinicalCareIntensity",
        "toColumn": "Code",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ]
      },
      {
        "name": "fad27816-0554-4cf8-8460-3cd094166774",
        "fromTable": "dbth Attendance",
        "fromColumn": "AttendanceDisposalCode",
        "toTable": "dbth AttendanceDisposal",
        "toColumn": "Code"
      },
      {
        "name": "9d9d5bff-4967-4cbd-856a-6fa5bb56a888",
        "fromTable": "dbth Episode",
        "fromColumn": "DateStart",
        "toTable": "Dates",
        "toColumn": "Date"
      },
      {
        "name": "05790d5e-ff88-49b3-b09e-1ff386ace3d0",
        "fromTable": "dbth Attendance",
        "fromColumn": "Site",
        "toTable": "dbth HospitalSite",
        "toColumn": "Code",
        "isActive": false
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.100.1401.0 (21.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dbth WardStay\",\"dbth Spell\",\"dbth SourceOfAdmission\",\"dbth Episode\",\"dbth DischargeMethod\",\"dbth DischargeDestination\",\"dbth AttendanceCategory\",\"dbth Attendance\",\"dbth AdmissionMethod\",\"dbth AdministrativeCategory\",\"dbth Ward\",\"dbth MainSpecialty\",\"dbth AttendanceDisposal\",\"dbth HospitalSite\",\"dbth WardIntendedAgeGroup\",\"dbth WardIntendedClinicalCareIntensity\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}