
    var minDate = min(dates[date])
    var maxDate = max(Dates[Date])
    return calculate( sumx('dbth episode', DATEDIFF( max(mindate, 'dbth Episode'[DateStart]), min(maxDate, 'dbth Episode'[DateEnd]), DAY)), FILTER('dbth WardStay', 'dbth WardStay'[Start] <= max(Dates[Date]) && 'dbth WardStay'[End] >= min(dates[date])))